---
- name: Configure CentOS 9 VM
  hosts: centos9
  become: true
  tasks:
    - name: Wait for port 22 to be open
      wait_for:
        port: 22
        timeout: 300
        state: started
        
    - name: Install required packages
      dnf:
        name:
          - git
        state: present

    - name: Create a user for automation
      user:
        name: devopsa
        shell: /bin/bash
        create_home: yes

    - name: Add sudo privileges for devops user
      lineinfile:
        path: /etc/sudoers.d/devopsa
        line: 'devopsa ALL=(ALL) NOPASSWD: ALL'
        create: yes
        mode: '0440'

