name: Destroy Deploy CentOS 9 on GCP and Configure via Ansible

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 

    env:
      TF_VAR_project_id: ""
      TF_VAR_credentials_file: "~/sec.json"
      TF_VAR_public_key_path: "~/.ssh/id_rsa.pub"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform and Ansible on CentOS 9
        run: |
          # Enable required repos
          sudo dnf install -y dnf-plugins-core epel-release
      
          # Install Ansible from EPEL
          sudo dnf install -y ansible
      
          # Add HashiCorp repo and install Terraform
          sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          sudo dnf -y install terraform
      
          # Confirm versions
          terraform -version
          ansible --version

      - name: Terraform Init
        run: |
          cd terraform-ansible
          terraform init

      - name: Terraform Destroy
        run: |
          cd terraform-ansible
          terraform destroy -auto-approve

